services:
  app:
    container_name: go-ticket
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=p
      - POSTGRES_DB=database
    ports:
      - '5432:5432'