name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO: ${{ secrets.DOCKER_REPO }}

jobs:

  build:
    name: Build Docker image and push it to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
      
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.0.0 
      
    - name: Docker Login
      run:  docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    
    - name: Build the Docker image # push The image to the docker hub
      run: docker build . --file Dockerfile --tag user/app:latest
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.0.0
      with:
        context: . 
        push: true
        tags: pmulieeee/go-ticket:latest
    
      

        
