name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

jobs:

  build:
    name: Build Docker image and push it to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
      
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.0.0 
      
    - name: Docker Login
      run:  docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
      
    - name: Build and push
      uses: docker/build-push-action@v3.0.0
      with:
        context: ./
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/private:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/private:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/private:buildcache,mode=max
        
